Controllers/MedicamentosController.cs
using CepdiRetoWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;


namespace CepdiRetoWeb.Controllers
{
    public class MedicamentosController : Controller
    {
        private readonly HttpClient? _httpClient;

        public MedicamentosController ( IHttpClientFactory httpClientFactory) 
        {
            _httpClient=httpClientFactory.CreateClient ();
            _httpClient.BaseAddress = new Uri("https://localhost:7069/api");
        }

        public async Task<IActionResult> Index()
        {

            var response = await _httpClient.GetAsync("api/Medicamentos/listaMedicamentos");

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var medicamentos= JsonConvert.DeserializeObject<IEnumerable<MedicamentosViewModel>>(content);
                return View("Index", medicamentos);
            }
            else
            {
                // Manejar el caso de error al obtener los detalles del medicamento.
                return View(new List<MedicamentosViewModel>());
            }
        }



        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(MedicamentosViewModel medicamento)
        {
            if (ModelState.IsValid)
            {
                var json = JsonConvert.SerializeObject(medicamento);
                var content = new StringContent(json, Encoding.UTF8, "application/json");

                var response = await _httpClient.PostAsync("/api/Medicamentos/crearMedicamento", content);

                if (response.IsSuccessStatusCode)
                {
                    // Manejar el caso de creación exitosa.
                    TempData["Success"] = "Medicamento agregado exitosamente!";
                    return RedirectToAction("Index");
                }
                else
                {
                    // Manejar el caso de error en la solicitud POST, por ejemplo, mostrando un mensaje de error.
                    ModelState.AddModelError(string.Empty, "Error al crear el medicamento.");
                }
            }
            return View(medicamento);
        }
        public async Task<IActionResult> Edit(int id)
        {

            var response = await _httpClient.GetAsync($"/api/Medicamentos/verMedicamento?id={id}");

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var medicamento = JsonConvert.DeserializeObject<MedicamentosViewModel>(content);

                // Devuelve la vista de edición con los detalles del Medicamento.
                return View(medicamento);
            }
            else
            {
                // Manejar el caso de error al obtener los detalles del Medicamento.
                return RedirectToAction("Details"); // Redirige a la página de lista de Medicamentos u otra acción apropiada.
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, MedicamentosViewModel medicamento)
        {
            if (ModelState.IsValid)
            {


                var json = JsonConvert.SerializeObject(medicamento);
                var content = new StringContent(json, Encoding.UTF8, "application/json");

                var response = await _httpClient.PutAsync($"/api/Medicamentos/editarMedicamento?id={id}", content);

                if (response.IsSuccessStatusCode)
                {
                    // Manejar el caso de actualización exitosa, por ejemplo, redirigiendo a la página de detalles del Medicamento.
                    TempData["Success"] = "Medicamento actualizado exitosamente!";
                    return RedirectToAction("Index", new { id });
                }
                else
                {
                    // Manejar el caso de error en la solicitud PUT o POST, por ejemplo, mostrando un mensaje de error.
                    ModelState.AddModelError(string.Empty, "Error al actualizar el medicamento.");
                }
            }

            // Si hay errores de validación, vuelve a mostrar el formulario de edición con los errores.
            return View(medicamento);
        }

        public async Task<IActionResult> Details(int id)
        {

            var response = await _httpClient.GetAsync($"/api/Medicamentos/verMedicamento?id={id}");


            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var medicamento = JsonConvert.DeserializeObject<MedicamentosViewModel>(content);

                // Devuelve la vista de edición con los detalles del Medicamento.
                return View(medicamento);
            }
            else
            {
                // Manejar el caso de error al obtener los detalles del Medicamento.
                return RedirectToAction("Details"); // Redirige a la página de lista de Medicamentos u otra acción apropiada.
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            var response = await _httpClient.DeleteAsync($"/api/Medicamentos/eliminarMedicamento?id={id}");

            if (response.IsSuccessStatusCode)
            {
                // Maneja el caso de eliminación exitosa, por ejemplo, redirigiendo a la página de lista de medicamentos.
                return RedirectToAction("Index");
            }
            else
            {
                // Maneja el caso de error en la solicitud DELETE, por ejemplo, mostrando un mensaje de error.
                TempData["Error"] = "Error al eliminar el medicamento.";
                return RedirectToAction("Index");
            }
        }
    }

}

Controllers/UploadController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Xml;
using WsCepdi;

namespace CepdiRetoApi.Controllers
{
    public class UploadController : Controller
    {


        private readonly ILogger<UploadController> _logger;

        public UploadController(ILogger<UploadController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult FileReader()
        { return View(); }


        [HttpPost]
        public async Task<IActionResult> FileReader(IFormFile file)
        {
            System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);

            // Upload File
            if (file != null && file.Length > 0 && file.FileName.Contains(".xml"))
            {
                var uploadDirectory = $"{Directory.GetCurrentDirectory()}\\wwwroot\\Uploads";

                if (!Directory.Exists(uploadDirectory))
                {
                    Directory.CreateDirectory(uploadDirectory);
                }

                var filePath = Path.Combine(uploadDirectory,"xmlSubido.xml");

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }

                TempData["Success"] = "Archivo cargado exitosamente!";
            }
            else 
            {
                TempData["Error"] = "Archivo no valido.!";
                
            }

            return View();
        }

        public async Task<IActionResult> getPDF()
        {
            //Read Xml
            var uuid = "";
            var filePath = $"{Directory.GetCurrentDirectory()}\\wwwroot\\Uploads\\xmlsubido.xml";
            XmlReader xmlReader = XmlReader.Create(filePath);
            while (xmlReader.Read())
            {
                if ((xmlReader.NodeType == XmlNodeType.Element) && (xmlReader.Name == "tfd:TimbreFiscalDigital"))
                {
                    if (xmlReader.HasAttributes)
                    {
                        uuid = xmlReader.GetAttribute("UUID");
                    }
                }
            }
            if (uuid != "" && uuid != null)
            {
                string usuario = "demo1@mail.com";
                string password = "Demo123#";
                WsCepdi.WSClient wSClient = new WSClient();

                var response = await wSClient.ObtenerPDFAsync(usuario, password, uuid.ToString());
                xmlReader.Close();
                xmlReader.Dispose();
                var contentType = "application/pdf;base64";
                return File(response.@return.PDF, contentType);
            }
            return View();
        }
    }

}

Controllers/UsuariosController.cs
using CepdiRetoWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace CepdiRetoWeb.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly HttpClient? _httpClient;

        public UsuariosController(IHttpClientFactory httpClientFactory)
        {
            _httpClient = httpClientFactory.CreateClient();
            _httpClient.BaseAddress = new Uri("https://localhost:7069/api");
        }

        public async Task<IActionResult> Index()
        {

            var response = await _httpClient.GetAsync("api/Usuarios/listaUsuarios");

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var usuarios = JsonConvert.DeserializeObject<IEnumerable<UsuariosViewModel>>(content);
                return View("Index", usuarios);
            }
            else
            {
                // Manejar el caso de error al obtener los detalles del usuario.
                return View(new List<UsuariosViewModel>());
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(UsuariosViewModel dUsuario)
        {
            if (ModelState.IsValid)
            {
                var json = JsonConvert.SerializeObject(dUsuario);
                var content = new StringContent(json, Encoding.UTF8, "application/json");

                var response = await _httpClient.PostAsync("/api/Usuarios/crearUsuario", content);

                if (response.IsSuccessStatusCode)
                {
                    // Manejar el caso de creación exitosa.
                    TempData["Success"] = "Usuario cargado exitosamente!";
                    return RedirectToAction("Index");
                }
                else
                {
                    // Manejar el caso de error en la solicitud POST, por ejemplo, mostrando un mensaje de error.
                    ModelState.AddModelError(string.Empty, "Error al crear el usuarios.");
                }
            }
            return View(dUsuario);
        }
        public async Task<IActionResult> Edit(int id)
        {

            var response = await _httpClient.GetAsync($"/api/Usuarios/verUsuario?id={id}");

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var usuario = JsonConvert.DeserializeObject<UsuariosViewModel>(content);

                // Devuelve la vista de edición con los detalles del usuario.
                return View(usuario);
            }
            else
            {
                // Manejar el caso de error al obtener los detalles del usuario
                
                return RedirectToAction("Details"); // Redirige a la página de lista de usuarios u otra acción apropiada.
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, UsuariosViewModel dUsuario)
        {
            if (ModelState.IsValid)
            {


                var json = JsonConvert.SerializeObject(dUsuario);
                var content = new StringContent(json, Encoding.UTF8, "application/json");

                var response = await _httpClient.PutAsync($"/api/Usuarios/editarUsuario?id={id}", content);

                if (response.IsSuccessStatusCode)
                {
                    // Manejar el caso de actualización exitosa, por ejemplo, redirigiendo a la página de detalles del Usuario.
                    TempData["Success"] = "Usuario actualizado exitosamente!";
                    return RedirectToAction("Index");
                }
                else
                {
                    // Manejar el caso de error en la solicitud PUT o POST, por ejemplo, mostrando un mensaje de error.
                    ModelState.AddModelError(string.Empty, "Error al actualizar el Usuario.");
                }
            }

            // Si hay errores de validación, vuelve a mostrar el formulario de edición con los errores.
            return View(dUsuario);
        }

        public async Task<IActionResult> Details(int id)
        {

            var response = await _httpClient.GetAsync($"/api/Usuarios/verUsuario?id={id}");


            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var usuario = JsonConvert.DeserializeObject<UsuariosViewModel>(content);

                // Devuelve la vista de edición con los detalles del Usuario.
                return View(usuario);
            }
            else
            {
                // Manejar el caso de error al obtener los detalles del Usuario.
                return RedirectToAction("Details"); // Redirige a la página de lista de Usuarios u otra acción apropiada.
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            var response = await _httpClient.DeleteAsync($"/api/Usuarios/eliminarUsuario?id={id}");

            if (response.IsSuccessStatusCode)
            {
                // Maneja el caso de eliminación exitosa, por ejemplo, redirigiendo a la página de lista de Usuarios.
                return RedirectToAction("Index");
            }
            else
            {
                // Maneja el caso de error en la solicitud DELETE, por ejemplo, mostrando un mensaje de error.
                TempData["Error"] = "Error al eliminar el usuario.";
                return RedirectToAction("Index");
            }
        }


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CepdiRetoWeb</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CepdiRetoWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="~/css/datatables.css">
    <link rel="stylesheet" type="text/css" href="~/css/dt-global_style.css" />
    <link href="~/css/plugins.css" rel="stylesheet" />
    <link href="~/css/perfect-scrollbar.css" rel="stylesheet" />
</head>
<body>
    <header class="container">
        <div class="topbar-nav header navbar" role="banner">
            <nav id="topbar" runat="server">
                <ul class="list-unstyled menu-categories" id="topAccordion">
                    <li class="menu">
                        <a asp-area="" asp-controller="Usuarios" asp-action="Index" class="dropdown-toggle">
                            <div class="">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" class="main-grid-item-icon" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                                    <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2" />
                                    <circle cx="9" cy="7" r="4" />
                                    <path d="M23 21v-2a4 4 0 0 0-3-3.87" />
                                    <path d="M16 3.13a4 4 0 0 1 0 7.75" />
                                </svg>
                                <span>Usuarios</span>
                            </div>
                        </a>
                    </li>
                    <li class="menu">
                        <a asp-controller="Medicamentos" asp-action="Index" class="dropdown-toggle">
                            <div class="">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" class="main-grid-item-icon" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                                    <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z" />
                                    <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z" />
                                </svg>
                                <span>Medicamentos</span>
                            </div>
                        </a>
                    </li>
                    <li class="menu">
                        <a asp-controller="Upload" asp-action="FileReader" class="dropdown-toggle">
                            <div class="">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" class="main-grid-item-icon" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                                    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                                    <polyline points="17 8 12 3 7 8" />
                                    <line x1="12" x2="12" y1="3" y2="15" />
                                </svg>
                                <span>Subir Archivo</span>
                            </div>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

@*     <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CepdiRetoWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/datatables.js"></script>
    <script src="~/js/perfect-scrollbar.min.js"></script>
    <script src="~/lib/materialize/js/materialize.min.js"></script>
    <script>
        $('#MyTable').DataTable({
            "dom": "<'dt--top-section'<'row'<'col-12 col-sm-6 d-flex justify-content-sm-start justify-content-center'l><'col-12 col-sm-6 d-flex justify-content-sm-end justify-content-center mt-sm-0 mt-3'f>>>" +
                "<'table-responsive'tr>" +
                "<'dt--bottom-section d-sm-flex justify-content-sm-between text-center'<'dt--pages-count  mb-sm-0 mb-3'i><'dt--pagination'p>>",
            "oLanguage": {
                "oPaginate": { "sPrevious": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>', "sNext": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>' },
                "sInfo": "P&aacutegina _PAGE_ of _PAGES_",
                "sSearch": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>',
                "sSearchPlaceholder": "Buscar...",
                "sLengthMenu": "Resultados :  _MENU_",
            },
            "stripeClasses": [],
            "lengthMenu": [10, 20, 50],
            "pageLength": 10
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>